const best = [
  {
    id: "best_01",
    name: "반팔 타마스 포켓 티셔츠 블랙",
    price: "88,000",
    code: "CA23SSTSSS00002019",
    percent: "",
    mainImg: "./images/best_01.jpg",
    detailImg01: "./images/detail01_1.jpg",
    detailImg02: "./images/detail01_2.jpg",
    detailImg03: "./images/detail01_3.jpg",
    detailImg04: "./images/detail01_4.jpg",
    detailImg05: "./images/detail01_5.jpg",
    colorImg01: "./images/best_02.jpg",
    colorImg02: "",
    colorImg03: "",
    relateImg: "./images/relateimg_01.jpg",
    relateImghover: "./images/relateimghover_01.jpg",
    relateName: "SINGLE KNEE CHROMO PANT DEARBORN",
    relateColor: "BLACK CHROMO",
    relatePrice: "156,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description:
      "S/S TAMAS POCKET T-SHIRT는 오가닉 코튼100% 싱글 저지 소재의 반팔 티셔츠입니다. 루즈 핏이며, 가슴 포켓이 있습니다. 후면에 그래픽 프린트가 있습니다.- 세탁 및 다림 시 그래픽의 손상 및 변형이 생길 수 있으므로, 뒤집어 세탁 및 다림을 권장합니다.",
  },
  {
    id: "best_02",
    name: "반팔 타마스 포켓 티셔츠 화이트",
    price: "88,000",
    code: "CA23SSTSSS00040025",
    percent: "",
    mainImg: "./images/best_02.jpg",
    detailImg01: "./images/detail02_1.jpg",
    detailImg02: "./images/detail02_2.jpg",
    detailImg03: "./images/detail02_3.jpg",
    detailImg04: "./images/detail02_4.jpg",
    detailImg05: "./images/detail02_5.jpg",
    colorImg01: "./images/best_01.jpg",
    colorImg02: "",
    colorImg03: "",
    relateImg: "./images/relateimg_02.jpg",
    relateImghover: "./images/relateimghover_02.jpg",
    relateName: "DOUBLE KNEE PANT FAIRFIELD",
    relateColor: "BLUE HEAVY STONE WASH",
    relatePrice: "173,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description:
      "DOUBLE KNEE PANT는 오가닉 코튼 100% 'FAIRFIELD' 데님 소재의 워크 팬츠입니다. 릴렉스드 스트레이트 핏에 밑위는 레귤러 웨이스트입니다. 전체적으로 트리플 스티칭 되있으며, 지퍼 플라이 형식입니다. 무릎 부분은 이중으로 덧대어져 있습니다. 제품 측면에는 툴 포켓, 해머 루프가 있으며, 후면 포켓에 스퀘어 라벨이 부착되어 있습니다.",
  },
  {
    id: "best_03",
    name: "싱글 니 쇼츠 스미스 블루 스톤 워시드",
    price: "135,000",
    code: "CA23SSSTWO00760001",
    percent: "",
    mainImg: "./images/mainimg_03.jpg",
    detailImg01: "./images/detail03_1.jpg",
    detailImg02: "./images/detail03_2.jpg",
    detailImg03: "./images/detail03_3.jpg",
    detailImg04: "./images/detail03_4.jpg",
    detailImg05: "./images/detail03_5.jpg",
    colorImg01: "./images/best_04.jpg",
    colorImg02: "",
    colorImg03: "",
    relateImg: "./images/relateimg_03.jpg",
    relateImghover: "./images/relateimghover_03.jpg",
    relateName: "S/S BLACK JACK SHIRT",
    relateColor: "BLACK JACK, BLACK",
    relatePrice: " 143,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description:
      "SINGLE KNEE SHORT는 면100% 'SMITH' 데님 소재의 워크 쇼츠입니다. 릴렉스드 핏에 밑위는 레귤러 웨이스트입니다. 전체적으로 트리플 스티칭 되있으며, 지퍼 플라이 형식입니다. 제품 측면에는 툴 포켓, 해머 루프가 있으며, 후면 포켓에 스퀘어 라벨이 부착되어 있습니다.",
  },
  {
    id: "best_04",
    name: "싱글 니 쇼츠 스미스 블루 스톤 블리치드",
    price: "148,000",
    code: "CA23SSSTWO00759001",
    percent: "",
    mainImg: "./images/best_04.jpg",
    detailImg01: "./images/detail04_1.jpg",
    detailImg02: "./images/detail04_2.jpg",
    detailImg03: "./images/detail04_3.jpg",
    detailImg04: "./images/detail04_4.jpg",
    detailImg05: "./images/detail04_5.jpg",
    colorImg01: "./images/best_03.jpg",
    colorImg02: "",
    colorImg03: "",
    relateImg: "./images/relateimg_04.jpg",
    relateImghover: "./images/relateimghover_04.jpg",
    relateName: "S/S COAST STATE T-SHIRT",
    relateColor: "WHITE",
    relatePrice: "98,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description:
      "SINGLE KNEE SHORT는 면100% 'SMITH' 데님 소재의 워크 쇼츠입니다. 릴렉스드 핏에 밑위는 레귤러 웨이스트입니다. 전체적으로 트리플 스티칭 되있으며, 지퍼 플라이 형식입니다. 제품 측면에는 툴 포켓, 해머 루프가 있으며, 후면 포켓에 스퀘어 라벨이 부착되어 있습니다.",
  },
  {
    id: "best_05",
    name: "코스탈 자켓 블랙/화이트",
    price: "248,000",
    code: "CA23SSJAJL00358002",
    percent: "",
    mainImg: "./images/best_05.jpg",
    detailImg01: "./images/detail05_1.jpg",
    detailImg02: "./images/detail05_2.jpg",
    detailImg03: "./images/detail05_3.jpg",
    detailImg04: "./images/detail05_4.jpg",
    detailImg05: "./images/detail05_5.jpg",
    colorImg01: "./images/best_07.jpg",
    relateImg: "./images/relateimg_05.jpg",
    relateImghover: "./images/relateimghover_05.jpg",
    relateName: "ISLAND SWIM TRUNKS",
    relateColor: "KIWI/BLACK",
    relatePrice: "108,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description:
      "COASTAL JACKET은 면100% 포플린 소재의 자켓입니다. 안감은 면 포플린 소재로 이루어져 있습니다. 후드는 팩커블 형태로 조절이 가능합니다. 정면은 지퍼와 스냅으로 여닫을 수 있습니다. 소매에 스크립트 자수가 있습니다.",
  },
  {
    id: "best_06",
    name: "아일랜드 스윔 트렁크 마리나 프린트",
    price: "123,000",
    code: "CA23SSSMSS11208001",
    percent: "",
    mainImg: "./images/best_06.jpg",
    detailImg01: "./images/detail06_1.jpg",
    detailImg02: "./images/detail06_2.jpg",
    detailImg03: "./images/detail06_3.jpg",
    detailImg04: "./images/detail06_4.jpg",
    detailImg05: "./images/detail06_5.jpg",
    relateImg: "./images/relateimg_06.jpg",
    relateImghover: "./images/relateimghover_06.jpg",
    relateName: "COAST STATE SWEATER",
    relateColor: "WHITE",
    relatePrice: "185,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description:
      "COAST STATE SWEATER는 면100% 소재의 스웨터입니다. 솔기 부분들이 오픈되어 있는 디테일이 있으며, 그래픽 자카드가 있습니다.",
  },
  //컬러추가
  {
    id: "best_07",
    name: "코스탈 자켓 화이트/블랙",
    price: " 248,000",
    code: "CA23SSJAJL00266002",
    percent: "",
    mainImg: "./images/best_07.jpg",
    detailImg01: "./images/detail07_1.jpg",
    detailImg02: "./images/detail07_2.jpg",
    detailImg03: "./images/detail07_3.jpg",
    detailImg04: "./images/detail07_4.jpg",
    detailImg05: "./images/detail07_5.jpg",
    relateImg: "./images/relateimg_07.jpg",
    relateImghover: "./images/relateimghover_07.jpg",
    relateName: "DOUBLE KNEE PANT FAIRFIELD",
    relateColor: "BLUE STONE WASHED",
    relatePrice: "158,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description:
      "COASTAL JACKET은 면100% 포플린 소재의 자켓입니다. 안감은 면 포플린 소재로 이루어져 있습니다. 후드는 팩커블 형태로 조절이 가능합니다. 정면은 지퍼와 스냅으로 여닫을 수 있습니다. 소매에 스크립트 자수가 있습니다.",
  },
  //컬러추가
  {
    id: "best_08",
    name: "콜 카고 쇼츠 모라가 키위 가먼트 다이드",
    price: " 148,000",
    code: "CA23SSSTCA11139001",
    percent: "",
    mainImg: "./images/best_08.jpg",
    detailImg01: "./images/detail08_1.jpg",
    detailImg02: "./images/detail08_2.jpg",
    detailImg03: "./images/detail08_3.jpg",
    detailImg04: "./images/detail08_4.jpg",
    detailImg05: "./images/detail08_5.jpg",
    relateImg: "./images/relateimg_07.jpg",
    relateImghover: "./images/relateimghover_07.jpg",
    relateName: "S/S SOUVENIR VALLEY T-SHIRT",
    relateColor: "NATURAL/BLACK",
    relatePrice: "95,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description:
      "COASTAL JACKET은 면100% 포플린 소재의 자켓입니다. 안감은 면 포플린 소재로 이루어져 있습니다. 후드는 팩커블 형태로 조절이 가능합니다. 정면은 지퍼와 스냅으로 여닫을 수 있습니다. 소매에 스크립트 자수가 있습니다.",
  },
  //컬러추가
]; //BEST
export default best;
