const products = [{
    name: "반팔 켄웨이 니트 폴로 블랙",
    engName: "S/S KENWAY KNIT POLO",
    category: "knit",
    color:"black",
    price: "148,000",
    soldOut: false,
    image: "./images/Top_01.jpg",
    hoverImage: "./images/Top_01_hover.jpg",
  },
  {
    name: "반팔 켄웨이 니트 폴로 네이비",
    engName: "S/S KENWAY KNIT POLO",
    category: "knit",
    color:"navy",
    price: "148,000",
    soldOut: false,
    image: "./images/Top_02.jpg",
    hoverImage: "./images/Top_02_hover.jpg",
  },
  {
    name: "반팔 켄웨이 니트 폴로 키위",
    engName: "S/S KENWAY KNIT POLO",
    category: "knit",
    color:"green",
    price: "148,000",
    soldOut: true,
    image: "./images/Top_03.jpg",
    hoverImage: "./images/Top_03_hover.jpg",
  },
  {
    name: "반팔 켄웨이 니트 폴로 화이트 스완",
    engName: "S/S KENWAY KNIT POLO",
    category: "knit",
    color:"white",
    price: "148,000",
    soldOut: false,
    image: "./images/Top_04.jpg",
    hoverImage: "./images/Top_04_hover.jpg",
  },
  {
    name: "반팔 이노베이션 포켓 티셔츠 블랙",
    engName: "S/S INNOVATION POCKET T-SHIRT",
    category: "t-shirt",
    color:"black",
    price: "85,000",
    soldOut: false,
    image: "./images/Top_05.jpg",
    hoverImage: "./images/Top_05_hover.jpg",
  },
  {
    name: "반팔 이노베이션 포켓 티셔츠 테이데",
    engName: "S/S INNOVATION POCKET T-SHIRT",
    category: "t-shirt",
    color:"light-brown",
    price: "85,000",
    soldOut: false,
    image: "./images/Top_06.jpg",
    hoverImage: "./images/Top_06_hover.jpg",
  },
  {
    name: "반팔 이노베이션 포켓 티셔츠 화이트",
    engName: "S/S INNOVATION POCKET T-SHIRT",
    category: "t-shirt",
    color:"white",
    price: "85,000",
    soldOut: false,
    image: "./images/Top_07.jpg",
    hoverImage: "./images/Top_07_hover.jpg",
  },
  {
    name: "반팔 라이프가즈 티셔츠 블랙",
    engName: "S/S LIFEGUARDS T-SHIRT",
    category: "t-shirt",
    color:"black",
    price: "75,000",
    soldOut: false,
    image: "./images/Top_08.jpg",
    hoverImage: "./images/Top_08_hover.jpg",
  },
  {
    name: "반팔 타마스 포켓 티셔츠 블랙",
    engName: "S/S TAMAS POCKET T-SHIRT",
    category: "t-shirt",
    color:"black",
    price: "88,000",
    soldOut: false,
    image: "./images/Top_09.jpg",
    hoverImage: "./images/Top_09_hover.jpg",
  },
  {
    name: "반팔 크래프트 셔츠 제우스 린스드",
    engName: "S/S CRAFT SHIRT",
    category: "shirt",
    color:"teal",
    price: "123,000",
    soldOut: false,
    image: "./images/Top_10.jpg",
    hoverImage: "./images/Top_10_hover.jpg",
  },
  {
    name: "반팔 크래프트 셔츠 쥐라 린스드",
    engName: "S/S WYNTON SHIRT",
    category: "shirt",
    color:"navy",
    price: "123,000",
    soldOut: false,
    image: "./images/Top_11.jpg",
    hoverImage: "./images/Top_11_hover.jpg",
  },
  {
    name: "반팔 윈튼 셔츠 타마린드/더스티 H",
    engName: "S/S WYNTON SHIRT",
    category: "shirt",
    color:"brown",
    price: "153,000",
    image: "./images/Top_12.jpg",
    hoverImage: "./images/Top_12_hover.jpg",
  },
  {
    name: "반팔 유니티 티셔츠 화이트",
    engName: "S/S UNITY T-SHIRT",
    category: "t-shirt",
    color:"white",
    price: "83,000",
    soldOut: false,
    image: "./images/Top_13.jpg",
    hoverImage: "./images/Top_13_hover.jpg",
  },
  {
    name: "반팔 유니티 티셔츠 블랙",
    engName: "S/S UNITY T-SHIRT",
    category: "t-shirt",
    color:"black",
    price: "83,000",
    soldOut: false,
    image: "./images/Top_14.jpg",
    hoverImage: "./images/Top_14_hover.jpg",
  },

  {
    name: "반팔 바칸제 티셔츠 피신",
    engName: "S/S VACANZE T-SHIRT",
    category: "t-shirt",
    color:"skyblue",
    price: "78,000",
    soldOut: false,
    image: "./images/Top_15.jpg",
    hoverImage: "./images/Top_15_hover.jpg",
  },
  {
    name: "반팔 바칸제 티셔츠 시트론",
    engName: "S/S VACANZE T-SHIRT",
    category: "t-shirt",
    color:"pale-yellow",
    price: "78,000",
    soldOut: false,
    image: "./images/Top_16.jpg",
    hoverImage: "./images/Top_16_hover.jpg",
  },
  {
    name: "반팔 말린 티셔츠 화이트",
    engName: "S/S MARLIN T-SHIRT",
    category: "t-shirt",
    color:"white",
    price: "78,000",
    soldOut: false,
    image: "./images/Top_17.jpg",
    hoverImage: "./images/Top_17_hover.jpg",
  },
  {
    name: "반팔 말린 티셔츠 라주라이트",
    engName: "S/S MARLIN T-SHIRT",
    category: "t-shirt",
    color:"blue",
    price: "78,000",
    soldOut: false,
    image: "./images/Top_18.jpg",
    hoverImage: "./images/Top_18_hover.jpg",
  },
  {
    name: "반팔 로커 티셔츠 애쉬 헤더/브라운",
    engName: "S/S LOCKER T-SHIRT",
    category: "t-shirt",
    color:"white",
    price: "62,400",
    soldOut: false,
    image: "./images/Top_19.jpg",
    hoverImage: "./images/Top_19_hover.jpg",
  },
  {
    name: "반팔 로커 티셔츠 블랙/화이트",
    engName: "S/S LOCKER T-SHIRT",
     category: "t-shirt", 
     color:"black",
    price: "62,400",
    soldOut: false,
    image: "./images/Top_20.jpg",
    hoverImage: "./images/Top_20_hover.jpg",
  },
  {
    name: "반팔 크로모 티셔츠 블랙 크로모",
    engName: "S/S CHROMO T-SHIRT",
     category: "t-shirt", 
     color:"navy",
    price: "70,400",
    soldOut: false,
    image: "./images/Top_21.jpg",
    hoverImage: "./images/Top_21_hover.jpg",
  },
  {
    name: "반팔 크로모 티셔츠 아말피 크로모",
    engName: "S/S CHROMO T-SHIRT",
     category: "t-shirt", 
     color:"skyblue",
    price: "70,400",
    soldOut: false,
    image: "./images/Top_22.jpg",
    hoverImage: "./images/Top_22_hover.jpg",
  },
  {
    name: "반팔 크로모 티셔츠 트리하우스 크로모",
    engName: "S/S CHROMO T-SHIRT",
     category: "t-shirt", 
     color:"green",
    price: "70,400",
    soldOut: false,
    image: "./images/Top_23.jpg",
    hoverImage: "./images/Top_23_hover.jpg",
  },
  {
    name: "반팔 넬슨 티셔츠 피신 가먼트 다이드",
    engName: "S/S NELSON T-SHIRT",
     category: "t-shirt", 
     color:"skyblue",
    price: "78,000",
    soldOut: false,
    image: "./images/Top_24.jpg",
    hoverImage: "./images/Top_24_hover.jpg",
  },

  {
    name: "반팔 넬슨 티셔츠 왁스 가먼트 다이드",
    engName: "S/S NELSON T-SHIRT",
     category: "t-shirt", 
     color:"white",
    price: "78,000",
    soldOut: false,
    image: "./images/Top_25.jpg",
    hoverImage: "./images/Top_25_hover.jpg",
  },

  {
    name: "반팔 마스터 셔츠 블랙",
    engName: "S/S MASTER SHIRT",
     category: "shirt", 
     color:"black",
    price: "113,000",
    soldOut: false,
    image: "./images/Top_26.jpg",
    hoverImage: "./images/Top_26_hover.jpg",
  },
  {
    name: "반팔 마스터 셔츠 테이데",
    engName: "S/S MASTER nSHIRT",
     category: "shirt", 
     color:"light-brown",
    price: "113,000",
    soldOut: false,
    image: "./images/Top_27.jpg",
    hoverImage: "./images/Top_27_hover.jpg",
  },
  {
    name: "디트로이트 자켓 블랙/블랙 린스드",
    engName: "DETROIT JACKET",
     category: "jacket", 
    price: "288,000",
    color:"black",
    soldOut: false,
    image: "./images/Top_28.jpg",
    hoverImage: "./images/Top_28_hover.jpg",
  },
  {
    name: "몬트레이 셔츠 자켓 키위 원 워시드",
    engName: "MONTEREY SHIRT JAC",
     category: "jacket", 
    price: "218,000",
    color:"green",
    soldOut: false,
    image: "./images/Top_29.jpg",
    hoverImage: "./images/Top_29_hover.jpg",
  },
  {
    name: "타일러 자켓 블랙",
    engName: "TYLER JACKET",
     category: "jacket",
     color:"black", 
    price: "254,400",
    soldOut: false,
    image: "./images/Top_30.jpg",
    hoverImage: "./images/Top_30_hover.jpg",
  },
  {
    name: "타일러 자켓 유카",
    engName: "TYLER JACKET",
     category: "jacket",
     color:"green", 
    price: "254,400",
    soldOut: false,
    image: "./images/Top_31.jpg",
    hoverImage: "./images/Top_31_hover.jpg",
  },
  {
    name: "바유 스웻셔츠 블랙 가먼트 다이드",
    engName: "BAYOU SWEATSHIRT",
     category: "shirt", 
     color:"teal",
    price: "158,400",
    soldOut: false,
    image: "./images/Top_32.jpg",
    hoverImage: "./images/Top_32_hover.jpg",
  },
  {
    name: "로커 스웻셔츠 블랙/화이트",
    engName: "LOCKER SWEATSHIRT",
     category: "shirt", 
     color:"black",
    price: "110,400",
    soldOut: false,
    image: "./images/Top_33.jpg",
    hoverImage: "./images/Top_33_hover.jpg",
  },
  {
    name: "로커 스웻셔츠 애쉬 헤더/브라운",
    engName: "LOCKER SWEATSHIRT",
     category: "shirt", 
     color:"white",
    price: "110,400",
    soldOut: false,
    image: "./images/Top_34.jpg",
    hoverImage: "./images/Top_34_hover.jpg",
  },
  {
    name: "로커 스웻셔츠 트리하우스/옐로우",
    engName: "LOCKER SWEATSHIRT",
     category: "shirt",
     color:"green", 
    price: "110,400",
    soldOut: false,
    image: "./images/Top_35.jpg",
    hoverImage: "./images/Top_35_hover.jpg",
  },
  {
    name: "후디드 크로모 스웻셔츠 블랙 ",
    engName: "HOODED CHROMO SWEATSHIRT",
     category: "shirt", 
     color:"navy",
    price: "166,400",
    soldOut: false,
    image: "./images/Top_36.jpg",
    hoverImage: "./images/Top_36_hover.jpg",
  },
  {
    name: "후디드 크로모 스웻셔츠 트리하우스",
    engName: "HOODED CHROMO SWEATSHIRT",
     category: "shirt", 
     color:"green",
    price: "166,400",
    soldOut: false,
    image: "./images/Top_37.jpg",
    hoverImage: "./images/Top_37_hover.jpg",
  },
  {
    name: "후디드 듀얼 스웻셔츠 애쉬 헤더",
    engName: "HOODED DUEL SWEATSHIRT",
     category: "shirt", 
     color:"white",
    price: "150,400",
    soldOut: false,
    image: "./images/Top_38.jpg",
    hoverImage: "./images/Top_38_hover.jpg",
  },
  {
    name: "후디드 듀얼 스웻셔츠 아가베",
    engName: "HOODED DUEL SWEATSHIRT",
     category: "shirt", 
     color:"green",
    price: " 150,400",
    soldOut: false,
    image: "./images/Top_39.jpg",
    hoverImage: "./images/Top_39_hover.jpg",
  },
  {
    name: "후디드 엘지 스웻셔츠 블랙/왁스",
    engName: "HOODED ELZY SWEATSHIRT",
     category: "shirt", 
     color:"black",
    price: "172,000",
    soldOut: false,
    image: "./images/Top_40.jpg",
    hoverImage: "./images/Top_40_hover.jpg",
  },
  {
    name: "후디드 엘지 스웻셔츠 해밀턴 브라운/토바코",
    engName: "HOODED ELZY SWEATSHIRT",
     category: "hood", 
     color:"brown",
    price: "172,000",
    soldOut: false,
    image: "./images/Top_41.jpg",
    hoverImage: "./images/Top_41_hover.jpg",
  },
  {
    name: "알링 자켓 블랙 페이디드",
    engName: "ARLING JACKET",
     category: "jacket", 
     color:"light-brown",
    price: "368,000",
    soldOut: false,
    image: "./images/Top_42.jpg",
    hoverImage: "./images/Top_42_hover.jpg",
  },
  {
    name: "스카일러 셔츠 자켓 블랙 가먼트 다이드",
    engName: "SKYLER SHIRT JAC",
     category: "jacket", 
     color:"black",
    price: "212,000",
    soldOut: false,
    image: "./images/Top_43.jpg",
    hoverImage: "./images/Top_43_hover.jpg",
  },
  {
    name: "스카일러 셔츠 자켓 스톰 블루 가먼트 다이드",
    engName: "STORM BLUE GARMENT DYED",
     category: "jacket", 
     color:"blue",
    price: "212,000",
    soldOut: false,
    image: "./images/Top_44.jpg",
    hoverImage: "./images/Top_44_hover.jpg",
  },
  {
    name: "미시건 코트 블랙 가먼트 다이드",
    engName: "BLACK GARMENT DYED",
     category: "jacket", 
     color:"blue",
    price: " 198,000",
    soldOut: false,
    image: "./images/Top_45.jpg",
    hoverImage: "./images/Top_45_hover.jpg",
  },
  {
    name: "미시건 코트 오프-화이트 린스드",
    engName: "MICHIGAN COAT",
     category: "jacket", 
     color:"white",
    price: "198,000",
    soldOut: false,
    image: "./images/Top_46.jpg",
    hoverImage: "./images/Top_46_hover.jpg",
  },
  {
    name: "미시건 코트 라주라이트/블랙 린스드",
    engName: "MICHIGAN COAT",
     category: "coat", 
     color:"blue",
    price: "228,000",
    soldOut: false,
    image: "./images/Top_47.jpg",
    hoverImage: "./images/Top_47_hover.jpg",
  },
  {
    name: "어웨이크 뉴욕 어웨이크 뉴욕 블랙 린스드",
    engName: "AWAKE NY OG ACTIVE JACKET",
     category: "hood", 
     color:"black",
    price: "388,000",
    soldOut: false,
    image: "./images/Top_48.jpg",
    hoverImage: "./images/Top_48_hover.jpg",
  },
  {
    name: "몬트레이 셔츠 자켓 블랙 스톤 워시드",
    engName: "MONTEREY SHIRT JAC",
     category: "shirt", 
    price: " 170,400",
    color:"black",
    soldOut: false,
    image: "./images/Top_49.jpg",
    hoverImage: "./images/Top_49_hover.jpg",
  },
  {
    name: "몬트레이 셔츠 자켓 블루 스톤 워시드",
    engName: "MONTEREY SHIRT JAC",
     category: "shirt",
     color:"blue", 
    price: "170,400",
    soldOut: false,
    image: "./images/Top_50.jpg",
    hoverImage: "./images/Top_50_hover.jpg",
  },
  {
    name: "아버 베스트 블랙 페이디드",
    engName: "ARBOR VEST",
    color:"light_brown",
     category: "vest", 
    price: "202,400",
    soldOut: false,
    image: "./images/Top_51.jpg",
    hoverImage: "./images/Top_51_hover.jpg",
  },
  {
    name: "아버 베스트 타마린드 페이디드",
    engName: "ARBOR VEST",
     category: "vest", 
     color:"brown",
    price: "202,400",
    soldOut: false,
    image: "./images/Top_52.jpg",
    hoverImage: "./images/Top_52_hover.jpg",
  },
  {
    name: "코스탈 자켓 블랙/화이트",
    engName: "COASTAL JACKET",
     category: "jacket", 
     color:"black",
    price: "248,000",
    soldOut: false,
    image: "./images/Top_53.jpg",
    hoverImage: "./images/Top_53_hover.jpg",
  },
  {
    name: "코스탈 자켓 화이트/블랙",
    engName: "COASTAL JACKET",
     category: "jacket", 
     color:"white",
    price: "248,000",
    soldOut: false,
    image: "./images/Top_54.jpg",
    hoverImage: "./images/Top_54_hover.jpg",
  },
  {
    name: "살레도 자켓 블랙 라이트 유즈드 워시",
    engName: "BLACK LIGHT USED WASH",
     category: "jacket",
     color:"gray", 
    price: "245,000",
    soldOut: false,
    image: "./images/Top_55.jpg",
    hoverImage: "./images/Top_55_hover.jpg",
  },
  {
    name: "살레도 자켓 블루 스톤 워시드",
    engName: "BLUE STONE WASHED",
     category: "jacket", 
     color:"blue",
    price: "208,000",
    soldOut: false,
    image: "./images/Top_56.jpg",
    hoverImage: "./images/Top_56_hover.jpg",
  },
  {
    name: "코스트 스테이트 스웻셔츠 애쉬 헤더",
    engName: "COAST STATE SWEATSHIRT",
     category: "shirt", 
     color:"white",
    price: "145,000",
    soldOut: false,
    image: "./images/Top_57.jpg",
    hoverImage: "./images/Top_57_hover.jpg",
  },
  {
    name: "넬슨 스웻셔츠 피신 가먼트 다이드",
    engName: "NELSON SWEATSHIRT",
     category: "shirt", 
     color:"skyblue",
    price: "130,400",
    soldOut: false,
    image: "./images/Top_58.jpg",
    hoverImage: "./images/Top_58_hover.jpg",
  },
  {
    name: "칼하트 스웨트셔츠 블랙/화이트",
    engName: "CARHARTT SWEATSHIRT",
     category: "shirt", 
     color:"black",
    price: "138,000",
    soldOut: false,
    image: "./images/Top_59.jpg",
    hoverImage: "./images/Top_59_hover.jpg",
  },
  {
    name: "칼하트 스웻셔츠 그레이 헤더/블랙",
    engName: "CARHARTT SWEATSHIRT",
     category: "shirt", 
     color:"gray",
    price: "138,000",
    soldOut: false,
    image: "./images/Top_60.jpg",
    hoverImage: "./images/Top_60_hover.jpg",
  },

  {
    name: "후디드 칼하트 스웻셔츠 제우스/비올란다",
    engName: "HOODED CARHARTT SWEATSHIRT",
     category: "shirt",
     color:"gray", 
    price: "118,400",
    soldOut: false,
    image: "./images/Top_61.jpg",
    hoverImage: "./images/Top_61_hover.jpg",
  },
  {
    name: "후디드 스퀘어 라벨 자켓 블랙",
    engName: "HOODED SQUARE LABEL JACKET",
     category: "jacket", 
     color:"black",
    price: "153,000",
    soldOut: false,
    image: "./images/Top_62.jpg",
    hoverImage: "./images/Top_62_hover.jpg",
  },
  {
    name: "후디드 스퀘어 라벨 자켓 그레이 헤더",
    engName: "HOODED SQUARE LABEL JACKET",
     category: "jacket", 
     color:"gray",
    price: "153,000",
    soldOut: false,
    image: "./images/Top_63.jpg",
    hoverImage: "./images/Top_63_hover.jpg",
  },
  {
    name: "후디드 스퀘어 라벨 자켓 해밀턴 브라운",
    engName: "HOODED SQUARE LABEL JACKET",
     category: "jacket",
     color:"brown", 
    price: "153,000",
    soldOut: false,
    image: "./images/Top_64.jpg",
    hoverImage: "./images/Top_64_hover.jpg",
  },
  {
    name: "후디드 매디슨 자켓 블랙/왁스",
    engName: "HOODED MADISON JACKET",
     category: "jacket", 
     color:"black",
    price: " 153,000",
    soldOut: false,
    image: "./images/Top_65.jpg",
    hoverImage: "./images/Top_65_hover.jpg",
  },
  {
    name: "알토 자켓 라주라이트",
    engName: "ALTO JACKET",
     category: "jacket", 
     color:"gray",
    price: "286,400",
    soldOut: false,
    image: "./images/Top_66.jpg",
    hoverImage: "./images/Top_66_hover.jpg",
  },
]; // subpage_top

const NEW = [{
    id: "new_01",
    name: "반팔 윈튼 셔츠 쥐라/유카 스톤 워시드",
    price: "153,000",
    code: "CA23SSSHSS11100001",
    accumulate: "",
    percent: "",
    mainImg: "./images/new_01.jpg",
    detailImg01: "./images/N_datail01_1.jpg",
    detailImg02: "./images/N_detail01_2.jpg",
    detailImg03: "./images/N_detail01_3.jpg",
    detailImg04: "./images/N_detail01_4.jpg",
    detailImg05: "./images/N_detail01_5.jpg",
    colorImg01: "./images/N_color01_1.jpg",
    colorImg02: "./images/N_color01_2.jpg",
    colorImg03: "",
    relateImg: "./images/N_realate01.jpg",
    relateImghover: "./images/N_relate01_hover.jpg",
    relateName: "LAWTON SHORT VESTAL",
    relateColor: "WALL",
    relatePrice: "148,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description: "S/S WYNTON SHIRT는 면100% 'COOSA' 립스탑 소재의 반팔 셔츠입니다. 레귤러 핏이며, 두개의 가슴 포켓은 플랩과 벨크로로 여닫을 수 있습니다. 후면에는 슬릿 디테일이 있으며, 정면 가슴 포켓에는 스퀘어 라벨이 부착되어 있습니다.",
  },

  {
    id: "new_02",
    name: "윈튼 쇼츠 쿠사 쥐라/유카 스톤 워시드",
    price: "153,000",
    code: "CA23SSSTOT11100001",
    accumulate: "",
    percent: "",
    mainImg: "./images/new_02.jpg",
    detailImg01: "./images/N_datail02_1.jpg",
    detailImg02: "./images/N_detail02_2.jpg",
    detailImg03: "./images/N_detail02_3.jpg",
    detailImg04: "./images/N_detail02_4.jpg",
    detailImg05: "./images/N_detail02_5.jpg",
    colorImg01: "./images/N_color02.jpg",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description: "WYNTON SHORT는 면100% 'COOSA' 립스탑 소재의 카고 반바지입니다. 릴렉스트 핏에 밑위는 레귤러 웨이스트입니다. . 허리 밴드는 신축성이 있으며, 조절식 벨트가 있습니다. 지퍼 플라이 형식입니다. 후면과 측면의 포켓은 플랩과 벨크로로 여닫을 수 있습니다. ",
  },

  {
    id: "new_03",
    name: "베이필드 버킷 햇 블랙 페이디드",
    price: "70,400",
    code: "CA23SSHEBC09320001",
    accumulate: "",
    percent: "",
    mainImg: "./images/new_03.jpg",
    detailImg01: "./images/N_datail03_1.jpg",
    detailImg02: "./images/N_detail03_2.jpg",
    detailImg05: "./images/N_detail03_5.jpg",
    colorImg01: "./images/N_color03.jpg",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description: "S/S WYNTON SHIRT는 면100% 'COOSA' 립스탑 소재의 반팔 셔츠입니다. 레귤러 핏이며, 두개의 가슴 포켓은 플랩과 벨크로로 여닫을 수 있습니다. 후면에는 슬릿 디테일이 있으며, 정면 가슴 포켓에는 스퀘어 라벨이 부착되어 있습니다.",
  },

  {
    id: "new_04",
    name: "라운드 카라비너 유카",
    price: "25,000",
    code: "CA23SSACKC11080001",
    accumulate: "",
    percent: "",
    mainImg: "./images/new_01.jpg",
    detailImg01: "./images/N_datail04_1.jpg",
    detailImg02: "./images/N_detail04_2.jpg",
    colorImg01: "./images/N_color_04_1.jpg",
    colorImg02: "./images/N_color_04_2.jpg",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description: "ROUND CARABINER는 아연 합금 소재의 카라비너입니다. 사이즈는 지름 5 CM로, 둥근 형태의 카라비너 입니다. 그래픽이 음각으로 새겨져 있습니다.",
  },

  {
    id: "new_05",
    name: "캔버스 6-패널 캡 블루핀/화이트 스톤 워시드",
    price: "65,000",
    code: "CA23SSHECP11278001",
    accumulate: "",
    percent: "",
    mainImg: "./images/new_05.jpg",
    detailImg01: "./images/N_datail05_1.jpg",
    detailImg02: "./images/N_detail05_2.jpg",
    detailImg03: "./images/N_detail05_3.jpg",
    colorImg01: "./images/N_color_05.jpg",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description: "BAYFIELD BUCKET HAT은 오가닉 코튼100% ;DEARBORN' 캔버스 소재의 버킷햇입니다. 안감이 있으며, 정면에 스퀘어 라벨이 부착되어 있습니다.",
  },

  {
    id: "new_06",
    name: "베이필드 토트 스톰 블루 페이디드",
    price: "86,400",
    code: "CA23SSBATT11085001",
    accumulate: "",
    percent: "",
    mainImg: "./images/new_06.jpg",
    detailImg01: "./images/N_datail06_1.jpg",
    detailImg02: "./images/N_detail06_2.jpg",
    detailImg03: "./images/N_detail06_3.jpg",
    detailImg04: "./images/N_detail06_4.jpg",
    detailImg05: "./images/N_detail06_5.jpg",
    colorImg01: "./images/N_color_06.jpg",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description: "BAYFIELD TOTE SMALL은 오가닉 코튼100% 'DEARBORN' 캔버스 소재의 토트백입니다. 36 X 34 X 12 CM 크기로 14.6 리터의 수납이 가능합니다. 안감이 없고, 스냅으로 여닫을 수 있습니다. 내부에 지퍼가 달린 포켓이 있으며, 정면에는 스퀘어 라벨이 부착된 포켓이 있습니다.",
  },

  {
    id: "new_07",
    name: "여성 반팔 로빌리아 셔츠 블루 스톤 워시드",
    price: "138,000",
    code: "CA23SSSHSS00760001",
    accumulate: "",
    percent: "",
    mainImg: "./images/new_07.jpg",
    detailImg01: "./images/N_datail07_1.jpg",
    detailImg02: "./images/N_detail07_2.jpg",
    detailImg03: "./images/N_detail07_3.jpg",
    detailImg04: "./images/N_detail07_4.jpg",
    detailImg05: "./images/N_detail07_5.jpg",
    relateImg: "./images/N_realate07.jpg",
    relateImghover: "./images/N_relate07_hover.jpg",
    relateName: "W MASTER SKIRTL",
    relateColor: "BLACK RINSED",
    relatePrice: " 118,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description: "W S/S LOVILIA SHIRT는 면100% 'PERRY' 데님 소재의 반팔 셔츠입니다. 루즈 핏이며, 가슴 포켓에 스퀘어 라벨이 부착되어 있습니다.",
  },
  {
    id: "new_08",
    name: "여성 알마 팬츠 블루 스톤 워시드",
    price: "155,000",
    code: "CA23SSPAWO00760008",
    accumulate: "",
    percent: "",
    mainImg: "./images/new_01.jpg",
    detailImg01: "./images/N_datail08_1.jpg",
    detailImg02: "./images/N_detail08_2.jpg",
    detailImg03: "./images/N_detail08_3.jpg",
    detailImg04: "./images/N_detail08_4.jpg",
    detailImg05: "./images/N_detail08_5.jpg",
    colorImg01: "./images/N_color01_1.jpg",
    colorImg02: "./images/N_color01_2.jpg",
    colorImg03: "",
    relateImg: "./images/N_realate08.jpg",
    relateImghover: "./images/N_relate08_hover.jpg",
    relateName: "W SALEDO JACKET",
    relateColor: "NATURAL STONE WASHED",
    relatePrice: "218,000",
    recentImg: "",
    recentName: "",
    recentColor: "",
    recentPrice: "",
    description: "W ALMA PANT는 면100% 'PERRY' 데님 소재의 워크 팬츠입니다. 루즈 테이퍼드 핏에 밑위는 하이 웨이스트입니다. 데님과 립스탑 소재가 믹스되어 있는 디테일이 있습니다. 무릎 부분은 패치로 덧대여져 있습니다. 지퍼 플라이 형식이며, 제품 측면에는 툴 포켓, 해머 루프가 있습니다. 후면 포켓에는 스퀘어 라벨이 부착되어 있습니다. ",
  },
]; //main_page NEW

export {
  products,
  NEW
};
